<div data-theme="" class="container mx-auto w-full">
    <div class="">

        <livewire:components.menu />

        <livewire:sections.hero />

        {{-- <div class="my-32 grid min-h-[70vh] grid-cols-8">

            <div class="col-span-3 flex flex-col gap-6">
                <h2 class="section -ms-[67px] flex items-center gap-6 border-s-4 ps-16 font-mono text-xl font-semibold">

                </h2>
                <div class="flex flex-col gap-6 ps-12">
                    <span>Lorem Ipsum</span>
                    <span>Lorem Ipsum</span>
                    <span>Lorem Ipsum</span>
                    <span>Lorem Ipsum</span>
                    <span>Lorem Ipsum</span>
                    <span>Lorem Ipsum</span>
                </div>
            </div>

            <div class="col-span-5 flex flex-col gap-6">

            </div>

        </div> --}}

        <!-- Featured Stacks Section -->
        <section class="bg-white py-20">
            <div class="container mx-auto px-6">
                <h2 class="mb-16 text-center text-4xl font-bold">Supported Stacks</h2>
                <div class="grid grid-cols-1 gap-8 md:grid-cols-3 lg:grid-cols-4">
                    <!-- Stack Card -->
                    <div class="card bg-base-100 w-96 shadow-sm">
                        <div class="card-body">
                            <figure class="mb-8 self-start">
                                <img src="{{ asset('images/stacks/tall.png') }}" alt="TALL Stack" draggable="false"
                                    class="size-24" />
                            </figure>

                            <h3 class="mb-2 text-2xl font-semibold">Laravel TALL</h3>
                            <p class="font-mono text-sm">Tailwind + Alpine + Livewire + Laravel</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <!-- Features Section -->
        <section class="my-20 py-20">
            <div class="container mx-auto px-6">
                <div class="grid gap-12 md:grid-cols-2">
                    <div class="flex flex-col space-y-6">
                        <h2 class="text-4xl font-bold">Your Project, Your Rules</h2>
                        <p class="text-lg text-gray-600">
                            Configure once, deploy everywhere. Stacker adapts to your workflow.
                        </p>
                        <ul class="space-y-6">
                            <li class="flex items-center space-x-4">
                                <div class="rounded-lg bg-green-100 p-3">⚡</div>
                                <div>
                                    <h3 class="text-lg font-semibold">Instant Setup</h3>
                                    <p class="text-gray-600">Create projects with pre-configured stacks in seconds</p>
                                </div>
                            </li>
                            <!-- Add more features -->
                        </ul>
                    </div>
                    <div class="bg-base-200 rounded-xl p-8">

                        <div class="mockup-code w-full">
                            <pre data-prefix="$"><code># .env.example</code></pre>
                            <pre data-prefix=">" class="text-success"><code>"My Stacker Project"</code></pre>
                            <pre data-prefix=">" class="text-warning"><code>mysql</code></pre>
                            <pre data-prefix=">"><code># Auto-generated by Stacker</code></pre>
                        </div>

                    </div>
                </div>
            </div>
        </section>

        <!-- CTA Section -->
        <section id="cta" class="rounded-box shadow-base bg-base-200 mb-20 py-20 shadow-lg">
            <div class="container mx-auto px-6 text-center">
                <h2 class="mb-8 text-4xl font-bold">Start Stacking Today</h2>
                <p class="mb-12 text-xl">Join thousands of developers saving hours every day</p>
                <div class="flex justify-center space-x-6">
                    <a href="#" class="btn btn-xl">
                        <x-fab-linux class="size-8" />
                    </a>
                    <a href="#" class="btn btn-xl">
                        <x-fab-windows class="size-8" />
                    </a>
                    <a href="#" class="btn btn-xl">
                        <x-fab-app-store-ios class="size-8" />
                    </a>
                </div>
            </div>
        </section>

        <livewire:sections.footer />

    </div>


</div>
